micronaut:
  application:
    name: pam-matchprofile-poc
    thread-selection: auto
  http:
    client:
      read-timeout: 300s
      max-content-length: 50485760
  metrics:
    enabled: true
    binders:
      uptime:
        enabled: true
      processor:
        enabled: true
      jvm:
        enabled: true
      web:
        enabled: true
      logback:
        enabled: true
      jdbc:
        enabled: true
      kafka:
        enabled: true
    export:
      prometheus:
        enabled: true
        step: PT1M
        descriptions: true
endpoints:
  metrics:
    enabled: true
  prometheus:
    sensitive: false
    enabled: true
  all:
    path: "/internal"

jackson:
  bean-introspection-module: true
  serialization:
    indentOutput: true

janzz:
  url: https://localhost/japi
  token: "token 123"

ad:
  apiUrl: https://pam-ad.intern.nav.no/api/v1
  searchApiUrl: https://pam-search-api.prod-gcp.nais.io
#datasources:
#  default:
#    url: ${DB_JDBC_URL:`jdbc:tc:postgresql:12:///puls?TC_INITSCRIPT=postgres/postgres-init.sql`}
#    driverClassName: ${DB_DRIVER:org.testcontainers.jdbc.ContainerDatabaseDriver}
#    username: ${DB_USERNAME:puls}
#    password: ${DB_PASSWORD:puls}
#    maximum-pool-size: 4
#    minimum-idle: 0
#    pool-name: default

#flyway:
#  datasources:
#    default:
#      locations: classpath:db/migration
#      #clean-on-validation-error: true

#kafka:
#  producers:
#    default:
#      linger.ms: 5000
#      batch.size: 65536

